### ISSUE TITLE
Failed to export some scenes

### ISSUE THREAD

**Issue by ghost** [lucasluqui/spiralview#2]
SpiralView fails to export Spiral Knights scene to XML.
I also attached the [output](https://github.com/lucas-allegri/spiralview/files/4355959/errout.txt).

**Comment by lucasluqui** [comment]
I tried to export a scene to XML using the latest spiralview version and it worked correctly (custom made level, not a cached one in the scenes folder). Some scenes might not be exportable due to incompatibilities with Spiral Knights code/configs, as some aren't exposed to clients (server exclusive, or simply not deployed on production).

Not much I can do, but I'll try to take a look into it in the future.

**Comment by ghost** [comment]
After some additional testing and observing I must agree. Some scenes are OK, like Haven Bazaar or Arcade, while others are missing dependencies.

I'll also look more into it if those configs can be found from some older builds or be stored on disk from server in some way.

EDIT: For a reason unknown to me, while validating scene the Vanaduke's Throne Room gives following err:
`references missing config of type scene_global: Boss Dungeon`
Although "Boss Dungeon" exists in scene_global. It's actually the very first configuration in the list.
